apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: argocd-cert-refresh-cronjob
spec:
  schedule: {{ $.Values.cronjob.schedule | quote }}
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: argocd-cert-refresh-sa
          serviceAccount: argocd-cert-refresh-sa
          containers:
          - name: argocd-cert-refresh-con
            image: {{ $.Values.image }}
            imagePullPolicy: IfNotPresent
            command: ["./argocd.sh"]
          restartPolicy: OnFailure