apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-cert-refresh-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argocd-cert-refresh-role
subjects:
- kind: ServiceAccount
  name: argocd-cert-refresh-sa
  namespace: devtroncd