apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $.Values.rolebinding.name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ $.Values.rolebinding.rolename }}
subjects:
- kind: ServiceAccount
  name: {{ $.Values.rolebinding.serviceaccount }}
  namespace: devtroncd