kubewatch:
  acdNamespace: devtroncd
  resources:
    requests:
      memory: 128Mi
      cpu: 100m
    limits:
      memory: 128Mi
      cpu: 100m
  image:
    name: quay.io/devtron/kubewatch
    tag: 8aef551d-128-2196