name: test-secret
type: kubernetes.io/dockerconfigjson
labels:
  test: chart
annotations:
  app: devtron-generic  
secrets:
  data:
  - key: db-username
    value: "root"
  - key: db-pass
    value: "1234567"
