apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-cm
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    app: svn-git-sync
data:
{{ toYaml $.Values.configs | indent 2 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    app: svn-git-sync
type: Opaque
data:
{{- range $k, $v := $.Values.secrets }}
  {{ $k }}: {{ $v | b64enc | quote }}
{{- end }}