apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
    release: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      release: {{ .Release.Name }}
  replicas: 1
  minReadySeconds: 60
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        release: {{ .Release.Name }}
    spec:
      {{- if $.Values.persistence.enabled }}
      volumes:
        - name: {{ .Release.Name }}-volume
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-pvc
      {{- end }}
      terminationGracePeriodSeconds: 30
      restartPolicy: Always
      serviceAccountName: {{ .Release.Name }}
      containers:
        - name: {{ .Release.Name }}
          image: {{ $.Values.image }}
          imagePullPolicy: {{ $.Values.imagePullPolicy }}
          envFrom:
          - configMapRef:
              name: {{ .Release.Name }}-cm
          - secretRef:
              name: {{ .Release.Name }}-secret
          volumeMounts:
            - name: {{ .Release.Name }}-volume
              mountPath: /app