{{- if or (eq .Values.installer.mode "full") (eq .Values.installer.mode "Full") }}
apiVersion: v1
kind: Secret
metadata:
  name: devtron-operator-secret
  namespace: devtroncd
type: Opaque
data:
{{- range $k, $v := .Values.secrets }}
  {{ $k }}: {{ $v | b64enc | quote }}
{{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: devtron-operator-cm
  namespace: devtroncd
data:
    {{- if .Values.configs }}
{{ toYaml $.Values.configs | indent 2 }}
    {{- end }}
    {{- if (semverCompare "<1.16-0" $.Capabilities.KubeVersion.GitVersion) }}
  ENABLE_LEGACY_API: "true"
    {{- end }}
  INSTALLATION_THROUGH_HELM: True
{{- end }}