{{- if or (eq .Values.installer.mode "hyperion") (eq .Values.installer.mode "Hyperion") }}
{{- with .Values.hyperion.devtron }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "devtron-cm"
  labels:
    release: devtron
  annotations:
    "helm.sh/resource-policy": keep
data:
  PG_USER: postgres
  PG_ADDR: postgresql-postgresql.devtroncd
  PG_PORT: "5432"
  HELM_CLIENT_URL: symbiote-service:50051
  DASHBOARD_PORT: "80"
  DASHBOARD_HOST: dashboard-service.devtroncd
  PG_DATABASE: orchestrator
  DEX_HOST: http://argocd-dex-server.devtroncd
  DEX_PORT: "5556"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: devtron
    release: devtron
  annotations:
    "helm.sh/resource-policy": keep
  name: devtron-service
  namespace: devtroncd
spec:
  ports:
  - name: devtron
    port: 80
    protocol: TCP
    targetPort: devtron
  selector:
    app: devtron
  sessionAffinity: None
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devtron
  labels:
    app: devtron
    release: devtron
  annotations:
    "helm.sh/resource-policy": keep
spec:
  selector:
    matchLabels:
      app: devtron
      release: devtron
  replicas: 1
  minReadySeconds: 60
  template:
    metadata:
      labels:
        app: devtron
        release: devtron
    spec:
      terminationGracePeriodSeconds: 30
      restartPolicy: Always
      serviceAccountName: devtron
      containers:
        - name: devtron
          image: {{ .image }}
          imagePullPolicy: {{ .imagePullPolicy }}
          ports:
            - name: devtron
              containerPort: 8080
              protocol: TCP
          env:
            - name: CONFIG_HASH
              value: 5525423a62b342ee763eb2e88dd40cfefd83f00e187a4ea2ff85dd39c00b6e01
            - name: SECRET_HASH
              value: fe216c236a95cf38868e5a08ef90f94e015e8842d79893e5214aa2cbccc27da4
            - name: DEVTRON_APP_NAME
              value: devtron
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          envFrom:
          - configMapRef:
              name: "devtron-cm"
          - secretRef:
              name: "devtron-secret"
  revisionHistoryLimit: 3
---
{{- if .serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: devtron-sm
  labels:
    kind: Prometheus
    app: devtron
    release: devtron
  annotations:
    "helm.sh/resource-policy": keep
spec:
  endpoints:
    - port: devtron
      path: /metrics
      scheme: http
      interval: 30s
      scrapeTimeout: 3s
  selector:
    matchLabels:
      app: devtron
{{- end }}
{{- end }}
{{- end }}