{{- with .Values.components.devtron.service }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: devtron
    release: devtron
    {{- if .labels }}
{{ toYaml .labels | indent 4 }}
    {{- end }}
  annotations:
    "helm.sh/resource-policy": keep
    {{- if .annotations }}
{{ toYaml .annotations | indent 4 }}
    {{- end }}
  name: devtron-service
  namespace: devtroncd
spec:
  ports:
  - name: devtron
    port: {{ .port }}
    {{- if .nodePort }}
    nodePort: {{ .nodePort }}
    {{- end }}
    protocol: TCP
    targetPort: devtron
  selector:
    app: devtron
  sessionAffinity: None
  type: {{ .type }}
{{- end }}