{{- if or (eq .Values.installer.mode "hyperion") (eq .Values.installer.mode "Hyperion") }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: devtron
  namespace: devtroncd
  labels:
    release: devtron
  annotations:
    "helm.sh/resource-policy": keep
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/instance: devtron
  name: devtron
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
- nonResourceURLs:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: devtron
  annotations:
    "helm.sh/resource-policy": keep
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: devtron
subjects:
  - kind: ServiceAccount
    name: devtron
    namespace: devtroncd
{{- end }}