{{- if or (eq .Values.installer.mode "hyperion") (eq .Values.installer.mode "Hyperion") }}
{{- with .Values.hyperion.symbiote }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: devtron
  namespace: devtroncd
  labels:
    release: devtron
  annotations:
    "helm.sh/resource-policy": keep
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: devtron
  annotations:
    "helm.sh/resource-policy": keep
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: devtron
    namespace: devtroncd
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: symbiote
  labels:
    app: symbiote
    chart: symbiote-4.11.1
  annotations:
    "helm.sh/resource-policy": keep
spec:
  selector:
    matchLabels:
      app: symbiote
  replicas: 1
  minReadySeconds: 60
  template:
    metadata:
      labels:
        app: symbiote
    spec:
      terminationGracePeriodSeconds: 30
      restartPolicy: Always
      serviceAccount: devtron
      containers:
        - name: symbiote
          image: {{ .image }}
          imagePullPolicy: {{ .imagePullPolicy }}
          ports:
            - name: app
              containerPort: 50051
              protocol: TCP
          env:
            - name: CONFIG_HASH
              value: d79e473c6352af87345c540cbbe1307c4cdc5a014f3393d3d46ff194442179e0
            - name: SECRET_HASH
              value: 552efd3342e616f7ff4a7d2fffd4879809af5efabeda4c1a8597aeafefcb017d
            - name: DEVTRON_APP_NAME
              value: symbiote
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
  revisionHistoryLimit: 3
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: symbiote
  name: symbiote-service
  namespace: devtroncd
  annotations:
    "helm.sh/resource-policy": keep
spec:
  ports:
    - name: app
      port: 50051
      protocol: TCP
      targetPort: app
  selector:
    app: symbiote
  sessionAffinity: None
  type: ClusterIP
{{- end }}
{{- end }}